Creat Assignment2
> makeVector <- function(x = numeric()) {
+ m <- NULL
+ set <- function(y) {
+ x <<- y
+ m <<- NULL
+ }
+ get <- function() x
+ setmean <- function(mean) m <<- mean
+ getmean <- function() m
+ list(set = set, get = get,
+ setmean = setmean,
+ getmean = getmean)
+ }
> cachemean <- function(x, ...) {
+ m <- x$getmean()
+ if(!is.null(m)) {
+ message("getting cached data")
+ return(m)
+ }
+ data <- x$get()
+ m <- mean(data, ...)
+ x$setmean(m)
+ m
+ }
> makeCacheMatrix
Error: object 'makeCacheMatrix' not found
> makeCacheMatrix(cachemean)
Error: could not find function "makeCacheMatrix"
> makeCacheMatrix <- function(x = matrix()) {
+ m <- NULL
+ y <- NULL
+ setmatrix <- function(y) {
+ x <<- y
+ m <<- NULL
+ }
+ list(list (set=set, get=get, setmatrix=setmatrix, getmatrix=getmatrix)
+ }
Error: unexpected '}' in:
"list(list (set=set, get=get, setmatrix=setmatrix, getmatrix=getmatrix)
}"
> makeCacheMatrix <- function(x = matrix()) {
+ m <- NULL
+ set <- function (y) {
+ x <<- y
+ m <<- NULL
+ }
+ get <-function() x
+ setmatrix <- function(solve) m<<- solve
+ getmatrix <- function() m
+ list (set=set, get=get, setmatrix=setmatrix, getmatrix=getmatrix)
+ }
> cacheSolve <- function(x, ...) {
+ m <- x$getmatrix()
+ if(!is.null(m)){
+ message("getting cached data")
+ return(m)
+ }
+ data <- x$get()
+ m <- solve(data,...)
+ x$setmatrix(m)
+ }
> n <- matrix(1:4,2,2)
> h <- makeCacheMatrix(n)
> cacheSolve(h)
> cacheSolve()
Error in cacheSolve() : argument "x" is missing, with no default
> cacheSolve(h)
getting cached data
     [,1] [,2]
[1,]   -2  1.5
[2,]    1 -0.5
getting cached data
     [,1] [,2]
[1,]   -2  1.5
[2,]    1 -0.5
> source('~/Data Science/R/programming assignment2/Assignment2.R')